### ISSUE TITLE
Usage of calendarize data on a page

### ISSUE THREAD

**Issue by bavarianbytes** [lochmueller/calendarize_pages#10] opened 2023-12-04 11:56 UTC
Hi!

Is there something prepared or any concept how to output the calendarize information (date, time, organizer, location, etc.) on a page?

Thx!

**Comment by lochmueller** [comment] 2023-12-04 15:09
Hey @bavarianbytes 

no not directly. If you are in a Fluid context and has already access to the Page Object, the ViewHelpres like https://github.com/lochmueller/calendarize/blob/master/Classes/ViewHelpers/IndicesByObjectViewHelper.php could help. but I think the problem is the first step (build thr page object for the rendering).

I suggest a Standalone controller that handle this.

Regards,
Tim

**Comment by sypets** [comment] 2023-12-21 09:07
I don't know what you mean with "Standalone controller"? Do you suggest to create a content element for this?

If you are in a FLUIDTEMPLATE context, would that be possible to access that information? I have access to the uid in `{data.calendarize}` but would not be able to use that in Fluid context without the object, right? I am not sure how one would go about constructing the model from that. That could be done, e.g. with a data processor and passed to FLUIDTEMPLATE?

**Comment by bavarianbytes** [comment] 2023-12-21 09:10
I used a data processor to get the calendarize data of the page and pass it to the fluid context, like this:
```
dataProcessing {
	40 = TYPO3\CMS\Frontend\DataProcessing\DatabaseQueryProcessor
	40 {
		table = tx_calendarize_domain_model_index
		as = calendarize
	}
}
```

Check the data in fluid then (`<f:debug>{calendarize}</f:debug>`) and use it how you like.

**Comment by sypets** [comment] 2023-12-21 10:58
thanks @bavarianbytes that is helpful, but probably should be a little more restrictive, e.g.

```
40 = TYPO3\CMS\Frontend\DataProcessing\DatabaseQueryProcessor
40 {
      		table = tx_calendarize_domain_model_index
      		as = calendarize
      		where = {#foreign_table} = 'pages' AND {#end_date} >= CURDATE()
      		orderBy = start_date
      		max = 10
}

```

(see [TypoScript select](https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Functions/Select.html))

and maybe check the start / end time too ... (can do this in Fluid too but would be inefficient to fetch many additional records).

**Comment by bavarianbytes** [comment] 2023-12-21 11:00
Thanks! (It was just my first draft)

**Comment by sypets** [comment] 2023-12-21 11:13
I understand. But maybe other people reading too ...

**Comment by lochmueller** [comment] 2024-12-19 14:34
I will close this issue. If we need any modifications for the extension, feel free to send PRs.

**Closed as completed by lochmueller** 2024-12-19 14:34 UTC
